[build]
  publish = "."
  command = "echo 'Static site ready'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://wlysmdboyeybprkgyaug.supabase.co/functions/v1/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://js.stripe.com; connect-src 'self' https://*.supabase.co https://api.stripe.com https://*.make.com; frame-src 'self' https://js.stripe.com; style-src 'self' 'unsafe-inline'"